// Utility for server-side CAPTCHA verification and anti-replay defense

// In-memory set of consumed tokens to prevent replay attacks (TTL: 10 minutes)
const consumedTokens = new Map();

// In-memory phone number cooldown to prevent phone call bombing / spamming (TTL: 15 minutes)
const phoneCooldowns = new Map();

const TOKEN_TTL_MS = 10 * 60 * 1000;
const PHONE_COOLDOWN_MS = 15 * 60 * 1000;

function cleanupOldEntries() {
  const now = Date.now();
  for (const [tok, exp] of consumedTokens.entries()) {
    if (now > exp) consumedTokens.delete(tok);
  }
  for (const [phone, exp] of phoneCooldowns.entries()) {
    if (now > exp) phoneCooldowns.delete(phone);
  }
}

// Clean up every 5 minutes
if (typeof setInterval !== "undefined") {
  setInterval(cleanupOldEntries, 5 * 60 * 1000).unref?.();
}

/**
 * Validates Cloudflare Turnstile token against Cloudflare's verification API.
 * Supports Cloudflare's official dummy test keys in dev/test if secret key is not set.
 */
export async function verifyTurnstileToken(token, clientIp) {
  if (!token || typeof token !== "string") {
    return { success: false, reason: "missing_token" };
  }

  const trimmed = token.trim();
  if (trimmed.length === 0) {
    return { success: false, reason: "empty_token" };
  }

  // Handle emergency fallback token (if user clicked interactive fallback button)
  if (trimmed.startsWith("fallback_")) {
    const parts = trimmed.split("_");
    const ts = Number(parts[1]);
    if (!isNaN(ts) && Date.now() - ts < 3 * 60 * 1000) {
      if (consumedTokens.has(trimmed)) {
        return { success: false, reason: "token_already_consumed" };
      }
      consumedTokens.set(trimmed, Date.now() + TOKEN_TTL_MS);
      return { success: true };
    }
    return { success: false, reason: "invalid_fallback_token" };
  }

  // Real Turnstile tokens generated by Cloudflare are long tokens (usually > 30 chars, max 2048)
  if (trimmed.length < 20 || trimmed.length > 2048) {
    return { success: false, reason: "invalid_token_format" };
  }

  // Check replay protection
  cleanupOldEntries();
  if (consumedTokens.has(trimmed)) {
    return { success: false, reason: "token_already_consumed" };
  }

  const secretKey =
    process.env.TURNSTILE_SECRET ||
    process.env.TURNSTILE_SECRET_KEY ||
    // Official Cloudflare testing secret (always passes with test sitekeys)
    "1x0000000000000000000000000000000AA";

  const expectedHostnames = new Set(
    (process.env.TURNSTILE_HOSTNAMES || "devmatesolutions.com,www.devmatesolutions.com,localhost,127.0.0.1")
      .split(",")
      .map((h) => h.trim().toLowerCase())
      .filter(Boolean)
  );

  try {
    const formData = new URLSearchParams();
    formData.append("secret", secretKey);
    formData.append("response", trimmed);
    if (clientIp && clientIp !== "unknown") {
      formData.append("remoteip", clientIp);
    }

    const verifyRes = await fetch(
      "https://challenges.cloudflare.com/turnstile/v0/siteverify",
      {
        method: "POST",
        body: formData,
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        signal: AbortSignal.timeout(10000),
      }
    );

    const outcome = await verifyRes.json();

    if (outcome.success) {
      // Validate hostname if provided by Cloudflare
      if (outcome.hostname && expectedHostnames.size > 0) {
        const returnedHost = outcome.hostname.toLowerCase();
        if (!expectedHostnames.has(returnedHost)) {
          console.warn(`[Turnstile] Hostname mismatch: received ${returnedHost}`);
          return { success: false, reason: "hostname_mismatch", hostname: returnedHost };
        }
      }

      // Mark token as consumed for replay protection
      consumedTokens.set(trimmed, Date.now() + TOKEN_TTL_MS);
      return { success: true, outcome };
    } else {
      console.warn("[Turnstile] siteverify rejected token:", outcome);
      return {
        success: false,
        reason: "verification_failed",
        errors: outcome["error-codes"],
      };
    }
  } catch (error) {
    console.error("[Turnstile] Error communicating with siteverify API:", error);
    if (process.env.NODE_ENV === "development") {
      consumedTokens.set(trimmed, Date.now() + TOKEN_TTL_MS);
      return { success: true, warned: true };
    }
    return { success: false, reason: "api_network_error" };
  }
}

/**
 * Checks and records phone cooldown to protect victim numbers from being bombed.
 * Allows at most 1 call submission per phone number every 15 minutes.
 */
export function checkPhoneCooldown(phone) {
  if (!phone) return { allowed: true };
  if (process.env.NODE_ENV === "development") {
    return { allowed: true };
  }
  const cleaned = phone.replace(/\D/g, "");
  if (cleaned.length < 6) return { allowed: true };

  cleanupOldEntries();
  const now = Date.now();
  const expiresAt = phoneCooldowns.get(cleaned);

  if (expiresAt && now < expiresAt) {
    const waitMins = Math.ceil((expiresAt - now) / 60000);
    return {
      allowed: false,
      reason: `A call request for this number was recently processed. Please wait ${waitMins} minute(s) before requesting again.`,
    };
  }

  phoneCooldowns.set(cleaned, now + PHONE_COOLDOWN_MS);
  return { allowed: true };
}
